<h1>Despre proiect</h1>
<h2>Totul despre acest proiect!</h2>

<p>iHazNews este un intermediar excelent intre siteurile de continut si utilizatori. Astfel, oferim detinatorilor siteurilor un serviciu impecabil de newsletter care poate fi adaugat fara efort iar clientii siteurilor in cauza sunt tinuti la curent cu ultimele stiri din domeniile lor de interes intr-un mod cat mai eficient si placut. iHazNews este extrem de usor de folosit , intuitiv dar complex in acelasi timp.</p>
<p>iHazNews ofera un newsletter foarte personalizat datorita faptului ca monitorizeaza activitatea utilizatorilor si ia decizii pe baza comportamentului acestora. Abonatii site-ului vor putea sa adauge preferinte , domenii de interes sau sa intre in diferite grupuri cu interese comune. Newletterul nu e niciodata prea incarcat pentru a mentine un nivel scazut de redundanta oferind in acelasi timp functionalitate maxima.</p>
<p>Proiectul a inceput ca un experiment al unor studenti ambitiosi dar lucrurile au evoluat si in cele din urma s-a ajuns la un serviciu de calitate care deja incepe sa devina popular. Suntem inca la inceput , de aceea apreciem orice idee sau sugestie pe care o aveti in gand.  </p>
