<h1>Echipa</h1>
<h2>Totul despre echipa noastră</h2>

<p>Echipa iHazNews este formata din studenti ai facultatii de Matematica si Informatica din cadrul Universitatii Bucuresti.</p>
<p>Cu totii suntem studenti in an terminal , in grupa 343.</p>
<p>Cine suntem noi ? </p>
<ul style="list-style-type:disc;padding:20px">
<li>Madalina Popescu</li>
<li>Alexandru Georoceanu</li>
<li>Sadeanu Valeriu</li>
<li>Moldoveanu Alexandru</li>
<li>Bejat Mihai</li>
<li>Draghia Stefan</li>
<li>Marin Sorin</li>
<li>Carpenco Tiberiu</li>
<li>Jingoiu George</li>
</ul>
