<h1>Bine ați venit.</h1>
<h2>Acesta este site-ul proiectului iHazNews</h2>
<p>
	Pentru a putea accesa site-ul nostru, trebuie sa fiti autentificat.<br/>
	
	Daca doriti sa va abonati la un newsltter personalizat, inregistrati-va cu un cont de utilizator.
	<br/>
	In schimb, daca doriti ca website-ul dumneaovoastra sa apara pe iHazNews, trebuie sa va inregistrati cu un cont de furnizor.
	<br/><br/>
	
	<!--<?php echo $page['content']; ?>-->
</p>

<!--
<div class="slider" style="width: 404px"></div>
-->