<h1>Home</h1>
<h2>Ultimul newsletter primit</h2>
<iframe src="/user/lastNewsletter" width="100%" height="100%" ></iframe>
<!--
<div style="width: 655px; float: left">
	<h1>Home</h1>
	<h2>Latest news on youre favorite topics</h2>
	<div class="contentNews1">
		<div class="time">21.03.2012</div>
		<h3>Aici 1</h3>
		<br/>
		<p>This text is styled with some of the text formatting properties. The heading uses the text-align, text-transform, and color properties. The paragraph is indented, aligned, and the space between characters is specified. The underline is removed from the "Try it yourself" link.</p>
	</div>
	<div class="contentNews2">
		<div class="time">21.02.2011</div>
		<h3>Aici 2</h3>
		<br/>
		<p>This text is styled with some of the text formatting properties. The heading uses the text-align, text-transform, and color properties. The paragraph is indented, aligned, and the space between characters is specified. The underline is removed from the "Try it yourself" link.</p>
	</div>

	<div class="contentNews1">
		<div class="time">11.03.2011</div>
		<h3>Aici 3</h3>	
		<br/>
		<p>This text is styled with some of the text formatting properties. The heading uses the text-align, text-transform, and color properties. The paragraph is indented, aligned, and the space between characters is specified. The underline is removed from the "Try it yourself" link.</p>
	</div>
</div>
<div id="home-sidebar"> 
	<div class="home-sidebar-section"> 
		<h2>Top news</h2> 
		<ul> 
			<li><a href="http://jquery-ui.googlecode.com/files/jquery-ui-1.8.11.zip">Latest dev bundle <span>(1.8.11)</span></a></li> 
			<li><a href="/docs/Git">Fork jQuery UI on GitHub</a></li> 
			<li><a href="http://code.google.com/apis/libraries/devguide.html#jqueryUI">Google CDN for jQuery UI</a></li> 
			<li><a href="/development">Development status</a></li> 			
		</ul> 
	</div> 
	
	<div class="home-sidebar-section"> 
		<h2>We also recommend</h2> 
		<ul> 
			<li><a href="http://jquery-ui.googlecode.com/files/jquery-ui-1.8.11.zip">Latest dev bundle <span>(1.8.11)</span></a></li> 
			<li><a href="/docs/Git">Fork jQuery UI on GitHub</a></li> 
			<li><a href="http://code.google.com/apis/libraries/devguide.html#jqueryUI">Google CDN for jQuery UI</a></li> 
			<li><a href="/development">Development status</a></li> 
			<li><a href="http://wiki.jqueryui.com">Development &amp; planning wiki</a></li> 
		</ul> 
	</div> 
</div>
-->