<h1>Home - Administrare</h1>
<h2>Informatii</h2>
<br/>
Panoul de administrare permite:<br/><br/>
<li>
	<a href="/administrator/users">Administrare utilizatori</a>
</li>
<li>
	<a href="/administrator/websites">Administrare website-uri</a>
</li>
<li>
	<a href="/administrator/newsgroups">Administrare newsgroup-uri</a>
</li>
<li>
	<a href="/administrator/interese">Administrare domenii de interes</a>
</li>





<!--
<table class="zebra">
	<thead>
		<tr>
			<th style="width:150px">Data</th>
			<th style="text-align:left">Evenimentul</th>
			<th style="width:200px">Măsura luată</th>
		</tr>
	</thead>
	<tbody>
	<?php $i = 0; foreach($page['events'] as $e): ?>
		<tr <?php if ($i++%2) echo 'class="odd"'; ?>>
			<td style="text-align:center"><?php echo $e['date']; ?></td>
			<td><?php echo $e['message']; ?></td>
			<td><?php echo $e['measure']; ?></td>
		</tr>
	<?php endforeach; ?>
	</tbody>
</table>
<a href="/administrator">Log-ul complet..</a>
-->