<!doctype html> 
<html> 
<head> 
	<title>iHN Widget | Not allowed</title> 
	<style> 
	* { margin: 0; padding: 0; border: none; font-size: 1em; 
			font-family: VollkornRegular, 'Trebuchet MS', Verdana, sans-serif; }
	.error { font-weight: bold; color: red; font-size:85.5% } 
	input { float: right; color: #555;
			text-shadow: 0 1px 0 white;
			border: 1px solid #626262;
			background: #DDD; -moz-box-shadow: inset 2px 2px 1px #CDCDCD;
			-webkit-box-shadow: inset 2px 2px 1px #CDCDCD; box-shadow: inset 2px 2px 1px #CDCDCD;
			-webkit-border-radius: 0; -khtml-border-radius: 0;-moz-border-radius: 0;
			border-radius: 0; -moz-box-sizing: border-box; -webkit-box-sizing: border-box;
			-ms-box-sizing: border-box; box-sizing: border-box; outline: none;
			}
	input[type=submit] { padding: 2px 4px; float: none; /*border: 1px solid #ccc*/ }
	input[type=submit]:hover { color: black; cursor: pointer }
	</style>
</head>
<body class="error">
	<br /><br />
	<p>Tipul dvs. de cont nu poate folosi widget-ul.</p><br /><br />
	<p>Incercati cu un cont de utilizator!<br /> Puteti crea unul 
		<a target="_new" href="http://ihaznews.com/auth/register">aici</a>.</p>
	<br /><br />
	<form method="get" action="/widget/logout/site/<?php echo urlencode(rawurlencode($page['site'])); ?>">
		<input type="submit" value="Delogare" />
	</form>
</body>
</html>